CREATE TABLE IF NOT EXISTS config_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS config_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_document_id BIGINT NOT NULL,
    version_num INT NOT NULL,
    message VARCHAR(512),
    config_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_config_version_document
        FOREIGN KEY (config_document_id) REFERENCES config_document(id),
    CONSTRAINT uk_config_version_document_version
        UNIQUE (config_document_id, version_num)
);

CREATE TABLE IF NOT EXISTS generation_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_document_id BIGINT NOT NULL,
    config_version_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    output_text TEXT,
    output_file VARCHAR(512),
    error_text TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    CONSTRAINT fk_generation_job_document
        FOREIGN KEY (config_document_id) REFERENCES config_document(id),
    CONSTRAINT fk_generation_job_version
        FOREIGN KEY (config_version_id) REFERENCES config_version(id)
);

CREATE INDEX IF NOT EXISTS idx_generation_job_status ON generation_job(status);
CREATE INDEX IF NOT EXISTS idx_generation_job_created_at ON generation_job(created_at);
