# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import algsolver_pb2 as algsolver__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in algsolver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductEstimatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateCatalog = channel.unary_unary(
                '/algosolver.bridge.v1.ProductEstimator/GenerateCatalog',
                request_serializer=algsolver__pb2.GenerateCatalogRequest.SerializeToString,
                response_deserializer=algsolver__pb2.GenerateCatalogResponse.FromString,
                _registered_method=True)
        self.OptimizeCatalog = channel.unary_unary(
                '/algosolver.bridge.v1.ProductEstimator/OptimizeCatalog',
                request_serializer=algsolver__pb2.OptimizeCatalogRequest.SerializeToString,
                response_deserializer=algsolver__pb2.OptimizeCatalogResponse.FromString,
                _registered_method=True)
        self.RunPipeline = channel.unary_unary(
                '/algosolver.bridge.v1.ProductEstimator/RunPipeline',
                request_serializer=algsolver__pb2.RunPipelineRequest.SerializeToString,
                response_deserializer=algsolver__pb2.RunPipelineResponse.FromString,
                _registered_method=True)
        self.EstimateProducts = channel.unary_unary(
                '/algosolver.bridge.v1.ProductEstimator/EstimateProducts',
                request_serializer=algsolver__pb2.EstimateRequest.SerializeToString,
                response_deserializer=algsolver__pb2.EstimateResponse.FromString,
                _registered_method=True)


class ProductEstimatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateCatalog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OptimizeCatalog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductEstimatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateCatalog': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCatalog,
                    request_deserializer=algsolver__pb2.GenerateCatalogRequest.FromString,
                    response_serializer=algsolver__pb2.GenerateCatalogResponse.SerializeToString,
            ),
            'OptimizeCatalog': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimizeCatalog,
                    request_deserializer=algsolver__pb2.OptimizeCatalogRequest.FromString,
                    response_serializer=algsolver__pb2.OptimizeCatalogResponse.SerializeToString,
            ),
            'RunPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.RunPipeline,
                    request_deserializer=algsolver__pb2.RunPipelineRequest.FromString,
                    response_serializer=algsolver__pb2.RunPipelineResponse.SerializeToString,
            ),
            'EstimateProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateProducts,
                    request_deserializer=algsolver__pb2.EstimateRequest.FromString,
                    response_serializer=algsolver__pb2.EstimateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'algosolver.bridge.v1.ProductEstimator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('algosolver.bridge.v1.ProductEstimator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductEstimator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateCatalog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algosolver.bridge.v1.ProductEstimator/GenerateCatalog',
            algsolver__pb2.GenerateCatalogRequest.SerializeToString,
            algsolver__pb2.GenerateCatalogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OptimizeCatalog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algosolver.bridge.v1.ProductEstimator/OptimizeCatalog',
            algsolver__pb2.OptimizeCatalogRequest.SerializeToString,
            algsolver__pb2.OptimizeCatalogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algosolver.bridge.v1.ProductEstimator/RunPipeline',
            algsolver__pb2.RunPipelineRequest.SerializeToString,
            algsolver__pb2.RunPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EstimateProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algosolver.bridge.v1.ProductEstimator/EstimateProducts',
            algsolver__pb2.EstimateRequest.SerializeToString,
            algsolver__pb2.EstimateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
