spring.devtools.restart.enabled=false
spring.web.error.include-stacktrace=always
spring.web.error.include-binding-errors=always
spring.web.error.include-exception=true

logging.level.org.springframework.web=DEBUG
logging.level.com.algosolver=DEBUG

# Serve React app from root
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/algosolver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.python.executable=python
app.python.main-script=../python/main.py

app.grpc.python.host=localhost
app.grpc.python.port=50051